// Common cities database for autocomplete
export interface City {
  name: string;
  country: string;
  countryCode: string; // ISO country code (e.g., "DE", "GB", "US")
  displayName: string; // "City, CountryCode"
}

export const cities: City[] = [
  // Germany
  { name: "Berlin", country: "Germany", countryCode: "DE", displayName: "Berlin, DE" },
  { name: "Munich", country: "Germany", countryCode: "DE", displayName: "Munich, DE" },
  { name: "Hamburg", country: "Germany", countryCode: "DE", displayName: "Hamburg, DE" },
  { name: "Frankfurt", country: "Germany", countryCode: "DE", displayName: "Frankfurt, DE" },
  { name: "Cologne", country: "Germany", countryCode: "DE", displayName: "Cologne, DE" },
  { name: "Stuttgart", country: "Germany", countryCode: "DE", displayName: "Stuttgart, DE" },
  { name: "Düsseldorf", country: "Germany", countryCode: "DE", displayName: "Düsseldorf, DE" },
  { name: "Dortmund", country: "Germany", countryCode: "DE", displayName: "Dortmund, DE" },
  { name: "Essen", country: "Germany", countryCode: "DE", displayName: "Essen, DE" },
  { name: "Leipzig", country: "Germany", countryCode: "DE", displayName: "Leipzig, DE" },
  { name: "Bremen", country: "Germany", countryCode: "DE", displayName: "Bremen, DE" },
  { name: "Dresden", country: "Germany", countryCode: "DE", displayName: "Dresden, DE" },
  { name: "Hannover", country: "Germany", countryCode: "DE", displayName: "Hannover, DE" },
  { name: "Nuremberg", country: "Germany", countryCode: "DE", displayName: "Nuremberg, DE" },
  { name: "Duisburg", country: "Germany", countryCode: "DE", displayName: "Duisburg, DE" },
  { name: "Bochum", country: "Germany", countryCode: "DE", displayName: "Bochum, DE" },
  { name: "Wuppertal", country: "Germany", countryCode: "DE", displayName: "Wuppertal, DE" },
  { name: "Bielefeld", country: "Germany", countryCode: "DE", displayName: "Bielefeld, DE" },
  { name: "Bonn", country: "Germany", countryCode: "DE", displayName: "Bonn, DE" },
  { name: "Münster", country: "Germany", countryCode: "DE", displayName: "Münster, DE" },
  { name: "Karlsruhe", country: "Germany", countryCode: "DE", displayName: "Karlsruhe, DE" },
  { name: "Mannheim", country: "Germany", countryCode: "DE", displayName: "Mannheim, DE" },
  { name: "Augsburg", country: "Germany", countryCode: "DE", displayName: "Augsburg, DE" },
  { name: "Wiesbaden", country: "Germany", countryCode: "DE", displayName: "Wiesbaden, DE" },
  { name: "Gelsenkirchen", country: "Germany", countryCode: "DE", displayName: "Gelsenkirchen, DE" },
  { name: "Mönchengladbach", country: "Germany", countryCode: "DE", displayName: "Mönchengladbach, DE" },
  { name: "Braunschweig", country: "Germany", countryCode: "DE", displayName: "Braunschweig, DE" },
  { name: "Chemnitz", country: "Germany", countryCode: "DE", displayName: "Chemnitz, DE" },
  { name: "Kiel", country: "Germany", countryCode: "DE", displayName: "Kiel, DE" },
  { name: "Aachen", country: "Germany", countryCode: "DE", displayName: "Aachen, DE" },
  { name: "Halle", country: "Germany", countryCode: "DE", displayName: "Halle, DE" },
  { name: "Magdeburg", country: "Germany", countryCode: "DE", displayName: "Magdeburg, DE" },
  { name: "Freiburg", country: "Germany", countryCode: "DE", displayName: "Freiburg, DE" },
  { name: "Krefeld", country: "Germany", countryCode: "DE", displayName: "Krefeld, DE" },
  { name: "Lübeck", country: "Germany", countryCode: "DE", displayName: "Lübeck, DE" },
  { name: "Oberhausen", country: "Germany", countryCode: "DE", displayName: "Oberhausen, DE" },
  { name: "Erfurt", country: "Germany", countryCode: "DE", displayName: "Erfurt, DE" },
  { name: "Mainz", country: "Germany", countryCode: "DE", displayName: "Mainz, DE" },
  { name: "Rostock", country: "Germany", countryCode: "DE", displayName: "Rostock, DE" },
  { name: "Kassel", country: "Germany", countryCode: "DE", displayName: "Kassel, DE" },
  { name: "Hagen", country: "Germany", countryCode: "DE", displayName: "Hagen, DE" },
  { name: "Hamm", country: "Germany", countryCode: "DE", displayName: "Hamm, DE" },
  { name: "Saarbrücken", country: "Germany", countryCode: "DE", displayName: "Saarbrücken, DE" },
  { name: "Mülheim", country: "Germany", countryCode: "DE", displayName: "Mülheim, DE" },
  { name: "Potsdam", country: "Germany", countryCode: "DE", displayName: "Potsdam, DE" },
  { name: "Ludwigshafen", country: "Germany", countryCode: "DE", displayName: "Ludwigshafen, DE" },
  { name: "Oldenburg", country: "Germany", countryCode: "DE", displayName: "Oldenburg, DE" },
  { name: "Leverkusen", country: "Germany", countryCode: "DE", displayName: "Leverkusen, DE" },
  { name: "Osnabrück", country: "Germany", countryCode: "DE", displayName: "Osnabrück, DE" },
  { name: "Solingen", country: "Germany", countryCode: "DE", displayName: "Solingen, DE" },
  { name: "Heidelberg", country: "Germany", countryCode: "DE", displayName: "Heidelberg, DE" },
  { name: "Herne", country: "Germany", countryCode: "DE", displayName: "Herne, DE" },
  { name: "Neuss", country: "Germany", countryCode: "DE", displayName: "Neuss, DE" },
  { name: "Darmstadt", country: "Germany", countryCode: "DE", displayName: "Darmstadt, DE" },
  { name: "Paderborn", country: "Germany", countryCode: "DE", displayName: "Paderborn, DE" },
  { name: "Regensburg", country: "Germany", countryCode: "DE", displayName: "Regensburg, DE" },
  { name: "Ingolstadt", country: "Germany", countryCode: "DE", displayName: "Ingolstadt, DE" },
  { name: "Würzburg", country: "Germany", countryCode: "DE", displayName: "Würzburg, DE" },
  { name: "Fürth", country: "Germany", countryCode: "DE", displayName: "Fürth, DE" },
  { name: "Wolfsburg", country: "Germany", countryCode: "DE", displayName: "Wolfsburg, DE" },
  { name: "Offenbach", country: "Germany", countryCode: "DE", displayName: "Offenbach, DE" },
  { name: "Ulm", country: "Germany", countryCode: "DE", displayName: "Ulm, DE" },
  { name: "Heilbronn", country: "Germany", countryCode: "DE", displayName: "Heilbronn, DE" },
  { name: "Pforzheim", country: "Germany", countryCode: "DE", displayName: "Pforzheim, DE" },
  { name: "Göttingen", country: "Germany", countryCode: "DE", displayName: "Göttingen, DE" },
  { name: "Bottrop", country: "Germany", countryCode: "DE", displayName: "Bottrop, DE" },
  { name: "Trier", country: "Germany", countryCode: "DE", displayName: "Trier, DE" },
  { name: "Recklinghausen", country: "Germany", countryCode: "DE", displayName: "Recklinghausen, DE" },
  { name: "Reutlingen", country: "Germany", countryCode: "DE", displayName: "Reutlingen, DE" },
  { name: "Bremerhaven", country: "Germany", countryCode: "DE", displayName: "Bremerhaven, DE" },
  { name: "Koblenz", country: "Germany", countryCode: "DE", displayName: "Koblenz, DE" },
  { name: "Bergisch Gladbach", country: "Germany", countryCode: "DE", displayName: "Bergisch Gladbach, DE" },
  { name: "Jena", country: "Germany", countryCode: "DE", displayName: "Jena, DE" },
  { name: "Remscheid", country: "Germany", countryCode: "DE", displayName: "Remscheid, DE" },
  { name: "Erlangen", country: "Germany", countryCode: "DE", displayName: "Erlangen, DE" },
  { name: "Moers", country: "Germany", countryCode: "DE", displayName: "Moers, DE" },
  { name: "Siegen", country: "Germany", countryCode: "DE", displayName: "Siegen, DE" },
  { name: "Hildesheim", country: "Germany", countryCode: "DE", displayName: "Hildesheim, DE" },
  { name: "Salzgitter", country: "Germany", countryCode: "DE", displayName: "Salzgitter, DE" },
  { name: "Kaiserslautern", country: "Germany", countryCode: "DE", displayName: "Kaiserslautern, DE" },
  
  // Iran
  { name: "Tehran", country: "Iran", countryCode: "IR", displayName: "Tehran, IR" },
  { name: "Mashhad", country: "Iran", countryCode: "IR", displayName: "Mashhad, IR" },
  { name: "Isfahan", country: "Iran", countryCode: "IR", displayName: "Isfahan, IR" },
  { name: "Karaj", country: "Iran", countryCode: "IR", displayName: "Karaj, IR" },
  { name: "Shiraz", country: "Iran", countryCode: "IR", displayName: "Shiraz, IR" },
  { name: "Tabriz", country: "Iran", countryCode: "IR", displayName: "Tabriz, IR" },
  { name: "Qom", country: "Iran", countryCode: "IR", displayName: "Qom, IR" },
  { name: "Ahvaz", country: "Iran", countryCode: "IR", displayName: "Ahvaz, IR" },
  { name: "Kermanshah", country: "Iran", countryCode: "IR", displayName: "Kermanshah, IR" },
  { name: "Urmia", country: "Iran", countryCode: "IR", displayName: "Urmia, IR" },
  { name: "Rasht", country: "Iran", countryCode: "IR", displayName: "Rasht, IR" },
  { name: "Zahedan", country: "Iran", countryCode: "IR", displayName: "Zahedan, IR" },
  { name: "Hamadan", country: "Iran", countryCode: "IR", displayName: "Hamadan, IR" },
  { name: "Kerman", country: "Iran", countryCode: "IR", displayName: "Kerman, IR" },
  { name: "Yazd", country: "Iran", countryCode: "IR", displayName: "Yazd, IR" },
  { name: "Ardabil", country: "Iran", countryCode: "IR", displayName: "Ardabil, IR" },
  { name: "Bandar Abbas", country: "Iran", countryCode: "IR", displayName: "Bandar Abbas, IR" },
  { name: "Arak", country: "Iran", countryCode: "IR", displayName: "Arak, IR" },
  { name: "Eslamshahr", country: "Iran", countryCode: "IR", displayName: "Eslamshahr, IR" },
  { name: "Zanjan", country: "Iran", countryCode: "IR", displayName: "Zanjan, IR" },
  { name: "Sanandaj", country: "Iran", countryCode: "IR", displayName: "Sanandaj, IR" },
  { name: "Qazvin", country: "Iran", countryCode: "IR", displayName: "Qazvin, IR" },
  { name: "Khorramabad", country: "Iran", countryCode: "IR", displayName: "Khorramabad, IR" },
  { name: "Gorgan", country: "Iran", countryCode: "IR", displayName: "Gorgan, IR" },
  { name: "Sabzevar", country: "Iran", countryCode: "IR", displayName: "Sabzevar, IR" },
  { name: "Khomeini Shahr", country: "Iran", countryCode: "IR", displayName: "Khomeini Shahr, IR" },
  { name: "Khorramshahr", country: "Iran", countryCode: "IR", displayName: "Khorramshahr, IR" },
  { name: "Sari", country: "Iran", countryCode: "IR", displayName: "Sari, IR" },
  { name: "Borujerd", country: "Iran", countryCode: "IR", displayName: "Borujerd, IR" },
  { name: "Najafabad", country: "Iran", countryCode: "IR", displayName: "Najafabad, IR" },
  { name: "Amol", country: "Iran", countryCode: "IR", displayName: "Amol, IR" },
  
  // USA - Major cities
  { name: "New York", country: "USA", countryCode: "US", displayName: "New York, US" },
  { name: "Los Angeles", country: "USA", countryCode: "US", displayName: "Los Angeles, US" },
  { name: "Chicago", country: "USA", countryCode: "US", displayName: "Chicago, US" },
  { name: "Houston", country: "USA", countryCode: "US", displayName: "Houston, US" },
  { name: "Phoenix", country: "USA", countryCode: "US", displayName: "Phoenix, US" },
  { name: "Philadelphia", country: "USA", countryCode: "US", displayName: "Philadelphia, US" },
  { name: "San Antonio", country: "USA", countryCode: "US", displayName: "San Antonio, US" },
  { name: "San Diego", country: "USA", countryCode: "US", displayName: "San Diego, US" },
  { name: "Dallas", country: "USA", countryCode: "US", displayName: "Dallas, US" },
  { name: "San Jose", country: "USA", countryCode: "US", displayName: "San Jose, US" },
  { name: "Austin", country: "USA", countryCode: "US", displayName: "Austin, US" },
  { name: "Jacksonville", country: "USA", countryCode: "US", displayName: "Jacksonville, US" },
  { name: "Fort Worth", country: "USA", countryCode: "US", displayName: "Fort Worth, US" },
  { name: "Columbus", country: "USA", countryCode: "US", displayName: "Columbus, US" },
  { name: "Charlotte", country: "USA", countryCode: "US", displayName: "Charlotte, US" },
  { name: "San Francisco", country: "USA", countryCode: "US", displayName: "San Francisco, US" },
  { name: "Indianapolis", country: "USA", countryCode: "US", displayName: "Indianapolis, US" },
  { name: "Seattle", country: "USA", countryCode: "US", displayName: "Seattle, US" },
  { name: "Denver", country: "USA", countryCode: "US", displayName: "Denver, US" },
  { name: "Washington", country: "USA", countryCode: "US", displayName: "Washington, US" },
  { name: "Boston", country: "USA", countryCode: "US", displayName: "Boston, US" },
  { name: "El Paso", country: "USA", countryCode: "US", displayName: "El Paso, US" },
  { name: "Nashville", country: "USA", countryCode: "US", displayName: "Nashville, US" },
  { name: "Detroit", country: "USA", countryCode: "US", displayName: "Detroit, US" },
  { name: "Oklahoma City", country: "USA", countryCode: "US", displayName: "Oklahoma City, US" },
  { name: "Portland", country: "USA", countryCode: "US", displayName: "Portland, US" },
  { name: "Las Vegas", country: "USA", countryCode: "US", displayName: "Las Vegas, US" },
  { name: "Memphis", country: "USA", countryCode: "US", displayName: "Memphis, US" },
  { name: "Louisville", country: "USA", countryCode: "US", displayName: "Louisville, US" },
  { name: "Baltimore", country: "USA", countryCode: "US", displayName: "Baltimore, US" },
  { name: "Milwaukee", country: "USA", countryCode: "US", displayName: "Milwaukee, US" },
  { name: "Albuquerque", country: "USA", countryCode: "US", displayName: "Albuquerque, US" },
  { name: "Tucson", country: "USA", countryCode: "US", displayName: "Tucson, US" },
  { name: "Fresno", country: "USA", countryCode: "US", displayName: "Fresno, US" },
  { name: "Sacramento", country: "USA", countryCode: "US", displayName: "Sacramento, US" },
  { name: "Kansas City", country: "USA", countryCode: "US", displayName: "Kansas City, US" },
  { name: "Mesa", country: "USA", countryCode: "US", displayName: "Mesa, US" },
  { name: "Atlanta", country: "USA", countryCode: "US", displayName: "Atlanta, US" },
  { name: "Omaha", country: "USA", countryCode: "US", displayName: "Omaha, US" },
  { name: "Colorado Springs", country: "USA", countryCode: "US", displayName: "Colorado Springs, US" },
  { name: "Raleigh", country: "USA", countryCode: "US", displayName: "Raleigh, US" },
  { name: "Miami", country: "USA", countryCode: "US", displayName: "Miami, US" },
  { name: "Long Beach", country: "USA", countryCode: "US", displayName: "Long Beach, US" },
  { name: "Virginia Beach", country: "USA", countryCode: "US", displayName: "Virginia Beach, US" },
  { name: "Oakland", country: "USA", countryCode: "US", displayName: "Oakland, US" },
  { name: "Minneapolis", country: "USA", countryCode: "US", displayName: "Minneapolis, US" },
  { name: "Tulsa", country: "USA", countryCode: "US", displayName: "Tulsa, US" },
  { name: "Tampa", country: "USA", countryCode: "US", displayName: "Tampa, US" },
  { name: "Cleveland", country: "USA", countryCode: "US", displayName: "Cleveland, US" },
  { name: "Wichita", country: "USA", countryCode: "US", displayName: "Wichita, US" },
  { name: "Arlington", country: "USA", countryCode: "US", displayName: "Arlington, US" },
  
  // UK - Major cities
  { name: "London", country: "UK", countryCode: "GB", displayName: "London, GB" },
  { name: "Birmingham", country: "UK", countryCode: "GB", displayName: "Birmingham, GB" },
  { name: "Manchester", country: "UK", countryCode: "GB", displayName: "Manchester, GB" },
  { name: "Glasgow", country: "UK", countryCode: "GB", displayName: "Glasgow, GB" },
  { name: "Liverpool", country: "UK", countryCode: "GB", displayName: "Liverpool, GB" },
  { name: "Leeds", country: "UK", countryCode: "GB", displayName: "Leeds, GB" },
  { name: "Sheffield", country: "UK", countryCode: "GB", displayName: "Sheffield, GB" },
  { name: "Edinburgh", country: "UK", countryCode: "GB", displayName: "Edinburgh, GB" },
  { name: "Bristol", country: "UK", countryCode: "GB", displayName: "Bristol, GB" },
  { name: "Cardiff", country: "UK", countryCode: "GB", displayName: "Cardiff, GB" },
  { name: "Belfast", country: "UK", countryCode: "GB", displayName: "Belfast, GB" },
  { name: "Newcastle", country: "UK", countryCode: "GB", displayName: "Newcastle, GB" },
  { name: "Nottingham", country: "UK", countryCode: "GB", displayName: "Nottingham, GB" },
  { name: "Leicester", country: "UK", countryCode: "GB", displayName: "Leicester, GB" },
  { name: "Coventry", country: "UK", countryCode: "GB", displayName: "Coventry, GB" },
  { name: "Bradford", country: "UK", countryCode: "GB", displayName: "Bradford, GB" },
  { name: "Sunderland", country: "UK", countryCode: "GB", displayName: "Sunderland, GB" },
  { name: "Wolverhampton", country: "UK", countryCode: "GB", displayName: "Wolverhampton, GB" },
  { name: "Plymouth", country: "UK", countryCode: "GB", displayName: "Plymouth, GB" },
  { name: "Stoke-on-Trent", country: "UK", countryCode: "GB", displayName: "Stoke-on-Trent, GB" },
  { name: "Reading", country: "UK", countryCode: "GB", displayName: "Reading, GB" },
  { name: "Derby", country: "UK", countryCode: "GB", displayName: "Derby, GB" },
  { name: "Southampton", country: "UK", countryCode: "GB", displayName: "Southampton, GB" },
  { name: "Northampton", country: "UK", countryCode: "GB", displayName: "Northampton, GB" },
  { name: "Portsmouth", country: "UK", countryCode: "GB", displayName: "Portsmouth, GB" },
  { name: "Luton", country: "UK", countryCode: "GB", displayName: "Luton, GB" },
  { name: "York", country: "UK", countryCode: "GB", displayName: "York, GB" },
  { name: "Swindon", country: "UK", countryCode: "GB", displayName: "Swindon, GB" },
  { name: "Peterborough", country: "UK", countryCode: "GB", displayName: "Peterborough, GB" },
  { name: "Cambridge", country: "UK", countryCode: "GB", displayName: "Cambridge, GB" },
  { name: "Oxford", country: "UK", countryCode: "GB", displayName: "Oxford, GB" },
  
  // France - Major cities
  { name: "Paris", country: "France", countryCode: "FR", displayName: "Paris, FR" },
  { name: "Marseille", country: "France", countryCode: "FR", displayName: "Marseille, FR" },
  { name: "Lyon", country: "France", countryCode: "FR", displayName: "Lyon, FR" },
  { name: "Toulouse", country: "France", countryCode: "FR", displayName: "Toulouse, FR" },
  { name: "Nice", country: "France", countryCode: "FR", displayName: "Nice, FR" },
  { name: "Nantes", country: "France", countryCode: "FR", displayName: "Nantes, FR" },
  { name: "Strasbourg", country: "France", countryCode: "FR", displayName: "Strasbourg, FR" },
  { name: "Montpellier", country: "France", countryCode: "FR", displayName: "Montpellier, FR" },
  { name: "Bordeaux", country: "France", countryCode: "FR", displayName: "Bordeaux, FR" },
  { name: "Lille", country: "France", countryCode: "FR", displayName: "Lille, FR" },
  { name: "Rennes", country: "France", countryCode: "FR", displayName: "Rennes, FR" },
  { name: "Reims", country: "France", countryCode: "FR", displayName: "Reims, FR" },
  { name: "Le Havre", country: "France", countryCode: "FR", displayName: "Le Havre, FR" },
  { name: "Saint-Étienne", country: "France", countryCode: "FR", displayName: "Saint-Étienne, FR" },
  { name: "Toulon", country: "France", countryCode: "FR", displayName: "Toulon, FR" },
  
  // Canada - Major cities
  { name: "Toronto", country: "Canada", countryCode: "CA", displayName: "Toronto, CA" },
  { name: "Vancouver", country: "Canada", countryCode: "CA", displayName: "Vancouver, CA" },
  { name: "Montreal", country: "Canada", countryCode: "CA", displayName: "Montreal, CA" },
  { name: "Calgary", country: "Canada", countryCode: "CA", displayName: "Calgary, CA" },
  { name: "Edmonton", country: "Canada", countryCode: "CA", displayName: "Edmonton, CA" },
  { name: "Ottawa", country: "Canada", countryCode: "CA", displayName: "Ottawa, CA" },
  { name: "Winnipeg", country: "Canada", countryCode: "CA", displayName: "Winnipeg, CA" },
  { name: "Quebec City", country: "Canada", countryCode: "CA", displayName: "Quebec City, CA" },
  { name: "Hamilton", country: "Canada", countryCode: "CA", displayName: "Hamilton, CA" },
  { name: "Kitchener", country: "Canada", countryCode: "CA", displayName: "Kitchener, CA" },
  
  // Other major cities
  { name: "Amsterdam", country: "Netherlands", countryCode: "NL", displayName: "Amsterdam, NL" },
  { name: "Rotterdam", country: "Netherlands", countryCode: "NL", displayName: "Rotterdam, NL" },
  { name: "The Hague", country: "Netherlands", countryCode: "NL", displayName: "The Hague, NL" },
  { name: "Utrecht", country: "Netherlands", countryCode: "NL", displayName: "Utrecht, NL" },
  { name: "Eindhoven", country: "Netherlands", countryCode: "NL", displayName: "Eindhoven, NL" },
  
  { name: "Brussels", country: "Belgium", countryCode: "BE", displayName: "Brussels, BE" },
  { name: "Antwerp", country: "Belgium", countryCode: "BE", displayName: "Antwerp, BE" },
  { name: "Ghent", country: "Belgium", countryCode: "BE", displayName: "Ghent, BE" },
  { name: "Bruges", country: "Belgium", countryCode: "BE", displayName: "Bruges, BE" },
  
  { name: "Zurich", country: "Switzerland", countryCode: "CH", displayName: "Zurich, CH" },
  { name: "Geneva", country: "Switzerland", countryCode: "CH", displayName: "Geneva, CH" },
  { name: "Basel", country: "Switzerland", countryCode: "CH", displayName: "Basel, CH" },
  { name: "Bern", country: "Switzerland", countryCode: "CH", displayName: "Bern, CH" },
  
  { name: "Vienna", country: "Austria", countryCode: "AT", displayName: "Vienna, AT" },
  { name: "Graz", country: "Austria", countryCode: "AT", displayName: "Graz, AT" },
  { name: "Linz", country: "Austria", countryCode: "AT", displayName: "Linz, AT" },
  { name: "Salzburg", country: "Austria", countryCode: "AT", displayName: "Salzburg, AT" },
  
  { name: "Stockholm", country: "Sweden", countryCode: "SE", displayName: "Stockholm, SE" },
  { name: "Gothenburg", country: "Sweden", countryCode: "SE", displayName: "Gothenburg, SE" },
  { name: "Malmö", country: "Sweden", countryCode: "SE", displayName: "Malmö, SE" },
  
  { name: "Copenhagen", country: "Denmark", countryCode: "DK", displayName: "Copenhagen, DK" },
  { name: "Aarhus", country: "Denmark", countryCode: "DK", displayName: "Aarhus, DK" },
  { name: "Odense", country: "Denmark", countryCode: "DK", displayName: "Odense, DK" },
  
  { name: "Oslo", country: "Norway", countryCode: "NO", displayName: "Oslo, NO" },
  { name: "Bergen", country: "Norway", countryCode: "NO", displayName: "Bergen, NO" },
  { name: "Trondheim", country: "Norway", countryCode: "NO", displayName: "Trondheim, NO" },
  
  { name: "Helsinki", country: "Finland", countryCode: "FI", displayName: "Helsinki, FI" },
  { name: "Espoo", country: "Finland", countryCode: "FI", displayName: "Espoo, FI" },
  { name: "Tampere", country: "Finland", countryCode: "FI", displayName: "Tampere, FI" },
  
  { name: "Madrid", country: "Spain", countryCode: "ES", displayName: "Madrid, ES" },
  { name: "Barcelona", country: "Spain", countryCode: "ES", displayName: "Barcelona, ES" },
  { name: "Valencia", country: "Spain", countryCode: "ES", displayName: "Valencia, ES" },
  { name: "Seville", country: "Spain", countryCode: "ES", displayName: "Seville, ES" },
  { name: "Bilbao", country: "Spain", countryCode: "ES", displayName: "Bilbao, ES" },
  
  { name: "Rome", country: "Italy", countryCode: "IT", displayName: "Rome, IT" },
  { name: "Milan", country: "Italy", countryCode: "IT", displayName: "Milan, IT" },
  { name: "Naples", country: "Italy", countryCode: "IT", displayName: "Naples, IT" },
  { name: "Turin", country: "Italy", countryCode: "IT", displayName: "Turin, IT" },
  { name: "Palermo", country: "Italy", countryCode: "IT", displayName: "Palermo, IT" },
  { name: "Genoa", country: "Italy", countryCode: "IT", displayName: "Genoa, IT" },
  { name: "Bologna", country: "Italy", countryCode: "IT", displayName: "Bologna, IT" },
  { name: "Florence", country: "Italy", countryCode: "IT", displayName: "Florence, IT" },
  
  { name: "Sydney", country: "Australia", countryCode: "AU", displayName: "Sydney, AU" },
  { name: "Melbourne", country: "Australia", countryCode: "AU", displayName: "Melbourne, AU" },
  { name: "Brisbane", country: "Australia", countryCode: "AU", displayName: "Brisbane, AU" },
  { name: "Perth", country: "Australia", countryCode: "AU", displayName: "Perth, AU" },
  { name: "Adelaide", country: "Australia", countryCode: "AU", displayName: "Adelaide, AU" },
  
  { name: "Tokyo", country: "Japan", countryCode: "JP", displayName: "Tokyo, JP" },
  { name: "Yokohama", country: "Japan", countryCode: "JP", displayName: "Yokohama, JP" },
  { name: "Osaka", country: "Japan", countryCode: "JP", displayName: "Osaka, JP" },
  { name: "Nagoya", country: "Japan", countryCode: "JP", displayName: "Nagoya, JP" },
  { name: "Sapporo", country: "Japan", countryCode: "JP", displayName: "Sapporo, JP" },
  
  { name: "Beijing", country: "China", countryCode: "CN", displayName: "Beijing, CN" },
  { name: "Shanghai", country: "China", countryCode: "CN", displayName: "Shanghai, CN" },
  { name: "Guangzhou", country: "China", countryCode: "CN", displayName: "Guangzhou, CN" },
  { name: "Shenzhen", country: "China", countryCode: "CN", displayName: "Shenzhen, CN" },
  { name: "Chengdu", country: "China", countryCode: "CN", displayName: "Chengdu, CN" },
  
  { name: "Mumbai", country: "India", countryCode: "IN", displayName: "Mumbai, IN" },
  { name: "Delhi", country: "India", countryCode: "IN", displayName: "Delhi, IN" },
  { name: "Bangalore", country: "India", countryCode: "IN", displayName: "Bangalore, IN" },
  { name: "Hyderabad", country: "India", countryCode: "IN", displayName: "Hyderabad, IN" },
  { name: "Chennai", country: "India", countryCode: "IN", displayName: "Chennai, IN" },
  { name: "Kolkata", country: "India", countryCode: "IN", displayName: "Kolkata, IN" },
  { name: "Pune", country: "India", countryCode: "IN", displayName: "Pune, IN" },
  
  { name: "Singapore", country: "Singapore", countryCode: "SG", displayName: "Singapore, SG" },
  { name: "Dubai", country: "UAE", countryCode: "AE", displayName: "Dubai, AE" },
  { name: "Abu Dhabi", country: "UAE", countryCode: "AE", displayName: "Abu Dhabi, AE" },
  { name: "Doha", country: "Qatar", countryCode: "QA", displayName: "Doha, QA" },
  { name: "Riyadh", country: "Saudi Arabia", countryCode: "SA", displayName: "Riyadh, SA" },
  { name: "Jeddah", country: "Saudi Arabia", countryCode: "SA", displayName: "Jeddah, SA" },
  
  { name: "São Paulo", country: "Brazil", countryCode: "BR", displayName: "São Paulo, BR" },
  { name: "Rio de Janeiro", country: "Brazil", countryCode: "BR", displayName: "Rio de Janeiro, BR" },
  { name: "Brasília", country: "Brazil", countryCode: "BR", displayName: "Brasília, BR" },
  { name: "Salvador", country: "Brazil", countryCode: "BR", displayName: "Salvador, BR" },
  
  { name: "Buenos Aires", country: "Argentina", countryCode: "AR", displayName: "Buenos Aires, AR" },
  { name: "Córdoba", country: "Argentina", countryCode: "AR", displayName: "Córdoba, AR" },
  
  { name: "Mexico City", country: "Mexico", countryCode: "MX", displayName: "Mexico City, MX" },
  { name: "Guadalajara", country: "Mexico", countryCode: "MX", displayName: "Guadalajara, MX" },
  { name: "Monterrey", country: "Mexico", countryCode: "MX", displayName: "Monterrey, MX" },
  
  { name: "São Paulo", country: "Brazil", countryCode: "BR", displayName: "São Paulo, BR" },
  { name: "Lima", country: "Peru", countryCode: "PE", displayName: "Lima, PE" },
  { name: "Bogotá", country: "Colombia", countryCode: "CO", displayName: "Bogotá, CO" },
  { name: "Santiago", country: "Chile", countryCode: "CL", displayName: "Santiago, CL" },
];

// Search function to filter cities based on query
export const searchCities = (query: string): City[] => {
  if (!query || query.length < 2) return [];
  
  const lowerQuery = query.toLowerCase().trim();
  
  return cities.filter(city => {
    const cityNameLower = city.name.toLowerCase();
    const countryLower = city.country.toLowerCase();
    const countryCodeLower = city.countryCode.toLowerCase();
    const displayNameLower = city.displayName.toLowerCase();
    
    // Match if query is found in city name, country, country code, or full display name
    return cityNameLower.includes(lowerQuery) || 
           countryLower.includes(lowerQuery) || 
           countryCodeLower.includes(lowerQuery) ||
           displayNameLower.includes(lowerQuery);
  }).slice(0, 10); // Limit to 10 results
};

