// Common cities database for autocomplete
export interface City {
  name: string;
  country: string;
  displayName: string; // "City, Country"
}

export const cities: City[] = [
  // Germany
  { name: "Berlin", country: "Germany", displayName: "Berlin, Germany" },
  { name: "Munich", country: "Germany", displayName: "Munich, Germany" },
  { name: "Hamburg", country: "Germany", displayName: "Hamburg, Germany" },
  { name: "Frankfurt", country: "Germany", displayName: "Frankfurt, Germany" },
  { name: "Cologne", country: "Germany", displayName: "Cologne, Germany" },
  { name: "Stuttgart", country: "Germany", displayName: "Stuttgart, Germany" },
  { name: "Düsseldorf", country: "Germany", displayName: "Düsseldorf, Germany" },
  { name: "Dortmund", country: "Germany", displayName: "Dortmund, Germany" },
  { name: "Essen", country: "Germany", displayName: "Essen, Germany" },
  { name: "Leipzig", country: "Germany", displayName: "Leipzig, Germany" },
  { name: "Bremen", country: "Germany", displayName: "Bremen, Germany" },
  { name: "Dresden", country: "Germany", displayName: "Dresden, Germany" },
  { name: "Hannover", country: "Germany", displayName: "Hannover, Germany" },
  { name: "Nuremberg", country: "Germany", displayName: "Nuremberg, Germany" },
  { name: "Duisburg", country: "Germany", displayName: "Duisburg, Germany" },
  { name: "Bochum", country: "Germany", displayName: "Bochum, Germany" },
  { name: "Wuppertal", country: "Germany", displayName: "Wuppertal, Germany" },
  { name: "Bielefeld", country: "Germany", displayName: "Bielefeld, Germany" },
  { name: "Bonn", country: "Germany", displayName: "Bonn, Germany" },
  { name: "Münster", country: "Germany", displayName: "Münster, Germany" },
  { name: "Karlsruhe", country: "Germany", displayName: "Karlsruhe, Germany" },
  { name: "Mannheim", country: "Germany", displayName: "Mannheim, Germany" },
  { name: "Augsburg", country: "Germany", displayName: "Augsburg, Germany" },
  { name: "Wiesbaden", country: "Germany", displayName: "Wiesbaden, Germany" },
  { name: "Gelsenkirchen", country: "Germany", displayName: "Gelsenkirchen, Germany" },
  { name: "Mönchengladbach", country: "Germany", displayName: "Mönchengladbach, Germany" },
  { name: "Braunschweig", country: "Germany", displayName: "Braunschweig, Germany" },
  { name: "Chemnitz", country: "Germany", displayName: "Chemnitz, Germany" },
  { name: "Kiel", country: "Germany", displayName: "Kiel, Germany" },
  { name: "Aachen", country: "Germany", displayName: "Aachen, Germany" },
  { name: "Halle", country: "Germany", displayName: "Halle, Germany" },
  { name: "Magdeburg", country: "Germany", displayName: "Magdeburg, Germany" },
  { name: "Freiburg", country: "Germany", displayName: "Freiburg, Germany" },
  { name: "Krefeld", country: "Germany", displayName: "Krefeld, Germany" },
  { name: "Lübeck", country: "Germany", displayName: "Lübeck, Germany" },
  { name: "Oberhausen", country: "Germany", displayName: "Oberhausen, Germany" },
  { name: "Erfurt", country: "Germany", displayName: "Erfurt, Germany" },
  { name: "Mainz", country: "Germany", displayName: "Mainz, Germany" },
  { name: "Rostock", country: "Germany", displayName: "Rostock, Germany" },
  { name: "Kassel", country: "Germany", displayName: "Kassel, Germany" },
  { name: "Hagen", country: "Germany", displayName: "Hagen, Germany" },
  { name: "Hamm", country: "Germany", displayName: "Hamm, Germany" },
  { name: "Saarbrücken", country: "Germany", displayName: "Saarbrücken, Germany" },
  { name: "Mülheim", country: "Germany", displayName: "Mülheim, Germany" },
  { name: "Potsdam", country: "Germany", displayName: "Potsdam, Germany" },
  { name: "Ludwigshafen", country: "Germany", displayName: "Ludwigshafen, Germany" },
  { name: "Oldenburg", country: "Germany", displayName: "Oldenburg, Germany" },
  { name: "Leverkusen", country: "Germany", displayName: "Leverkusen, Germany" },
  { name: "Osnabrück", country: "Germany", displayName: "Osnabrück, Germany" },
  { name: "Solingen", country: "Germany", displayName: "Solingen, Germany" },
  { name: "Heidelberg", country: "Germany", displayName: "Heidelberg, Germany" },
  { name: "Herne", country: "Germany", displayName: "Herne, Germany" },
  { name: "Neuss", country: "Germany", displayName: "Neuss, Germany" },
  { name: "Darmstadt", country: "Germany", displayName: "Darmstadt, Germany" },
  { name: "Paderborn", country: "Germany", displayName: "Paderborn, Germany" },
  { name: "Regensburg", country: "Germany", displayName: "Regensburg, Germany" },
  { name: "Ingolstadt", country: "Germany", displayName: "Ingolstadt, Germany" },
  { name: "Würzburg", country: "Germany", displayName: "Würzburg, Germany" },
  { name: "Fürth", country: "Germany", displayName: "Fürth, Germany" },
  { name: "Wolfsburg", country: "Germany", displayName: "Wolfsburg, Germany" },
  { name: "Offenbach", country: "Germany", displayName: "Offenbach, Germany" },
  { name: "Ulm", country: "Germany", displayName: "Ulm, Germany" },
  { name: "Heilbronn", country: "Germany", displayName: "Heilbronn, Germany" },
  { name: "Pforzheim", country: "Germany", displayName: "Pforzheim, Germany" },
  { name: "Göttingen", country: "Germany", displayName: "Göttingen, Germany" },
  { name: "Bottrop", country: "Germany", displayName: "Bottrop, Germany" },
  { name: "Trier", country: "Germany", displayName: "Trier, Germany" },
  { name: "Recklinghausen", country: "Germany", displayName: "Recklinghausen, Germany" },
  { name: "Reutlingen", country: "Germany", displayName: "Reutlingen, Germany" },
  { name: "Bremerhaven", country: "Germany", displayName: "Bremerhaven, Germany" },
  { name: "Koblenz", country: "Germany", displayName: "Koblenz, Germany" },
  { name: "Bergisch Gladbach", country: "Germany", displayName: "Bergisch Gladbach, Germany" },
  { name: "Jena", country: "Germany", displayName: "Jena, Germany" },
  { name: "Remscheid", country: "Germany", displayName: "Remscheid, Germany" },
  { name: "Erlangen", country: "Germany", displayName: "Erlangen, Germany" },
  { name: "Moers", country: "Germany", displayName: "Moers, Germany" },
  { name: "Siegen", country: "Germany", displayName: "Siegen, Germany" },
  { name: "Hildesheim", country: "Germany", displayName: "Hildesheim, Germany" },
  { name: "Salzgitter", country: "Germany", displayName: "Salzgitter, Germany" },
  { name: "Kaiserslautern", country: "Germany", displayName: "Kaiserslautern, Germany" },
  
  // Iran
  { name: "Tehran", country: "Iran", displayName: "Tehran, Iran" },
  { name: "Mashhad", country: "Iran", displayName: "Mashhad, Iran" },
  { name: "Isfahan", country: "Iran", displayName: "Isfahan, Iran" },
  { name: "Karaj", country: "Iran", displayName: "Karaj, Iran" },
  { name: "Shiraz", country: "Iran", displayName: "Shiraz, Iran" },
  { name: "Tabriz", country: "Iran", displayName: "Tabriz, Iran" },
  { name: "Qom", country: "Iran", displayName: "Qom, Iran" },
  { name: "Ahvaz", country: "Iran", displayName: "Ahvaz, Iran" },
  { name: "Kermanshah", country: "Iran", displayName: "Kermanshah, Iran" },
  { name: "Urmia", country: "Iran", displayName: "Urmia, Iran" },
  { name: "Rasht", country: "Iran", displayName: "Rasht, Iran" },
  { name: "Zahedan", country: "Iran", displayName: "Zahedan, Iran" },
  { name: "Hamadan", country: "Iran", displayName: "Hamadan, Iran" },
  { name: "Kerman", country: "Iran", displayName: "Kerman, Iran" },
  { name: "Yazd", country: "Iran", displayName: "Yazd, Iran" },
  { name: "Ardabil", country: "Iran", displayName: "Ardabil, Iran" },
  { name: "Bandar Abbas", country: "Iran", displayName: "Bandar Abbas, Iran" },
  { name: "Arak", country: "Iran", displayName: "Arak, Iran" },
  { name: "Eslamshahr", country: "Iran", displayName: "Eslamshahr, Iran" },
  { name: "Zanjan", country: "Iran", displayName: "Zanjan, Iran" },
  { name: "Sanandaj", country: "Iran", displayName: "Sanandaj, Iran" },
  { name: "Qazvin", country: "Iran", displayName: "Qazvin, Iran" },
  { name: "Khorramabad", country: "Iran", displayName: "Khorramabad, Iran" },
  { name: "Gorgan", country: "Iran", displayName: "Gorgan, Iran" },
  { name: "Sabzevar", country: "Iran", displayName: "Sabzevar, Iran" },
  { name: "Khomeini Shahr", country: "Iran", displayName: "Khomeini Shahr, Iran" },
  { name: "Khorramshahr", country: "Iran", displayName: "Khorramshahr, Iran" },
  { name: "Sari", country: "Iran", displayName: "Sari, Iran" },
  { name: "Borujerd", country: "Iran", displayName: "Borujerd, Iran" },
  { name: "Najafabad", country: "Iran", displayName: "Najafabad, Iran" },
  { name: "Amol", country: "Iran", displayName: "Amol, Iran" },
  
  // USA - Major cities
  { name: "New York", country: "USA", displayName: "New York, USA" },
  { name: "Los Angeles", country: "USA", displayName: "Los Angeles, USA" },
  { name: "Chicago", country: "USA", displayName: "Chicago, USA" },
  { name: "Houston", country: "USA", displayName: "Houston, USA" },
  { name: "Phoenix", country: "USA", displayName: "Phoenix, USA" },
  { name: "Philadelphia", country: "USA", displayName: "Philadelphia, USA" },
  { name: "San Antonio", country: "USA", displayName: "San Antonio, USA" },
  { name: "San Diego", country: "USA", displayName: "San Diego, USA" },
  { name: "Dallas", country: "USA", displayName: "Dallas, USA" },
  { name: "San Jose", country: "USA", displayName: "San Jose, USA" },
  { name: "Austin", country: "USA", displayName: "Austin, USA" },
  { name: "Jacksonville", country: "USA", displayName: "Jacksonville, USA" },
  { name: "Fort Worth", country: "USA", displayName: "Fort Worth, USA" },
  { name: "Columbus", country: "USA", displayName: "Columbus, USA" },
  { name: "Charlotte", country: "USA", displayName: "Charlotte, USA" },
  { name: "San Francisco", country: "USA", displayName: "San Francisco, USA" },
  { name: "Indianapolis", country: "USA", displayName: "Indianapolis, USA" },
  { name: "Seattle", country: "USA", displayName: "Seattle, USA" },
  { name: "Denver", country: "USA", displayName: "Denver, USA" },
  { name: "Washington", country: "USA", displayName: "Washington, USA" },
  { name: "Boston", country: "USA", displayName: "Boston, USA" },
  { name: "El Paso", country: "USA", displayName: "El Paso, USA" },
  { name: "Nashville", country: "USA", displayName: "Nashville, USA" },
  { name: "Detroit", country: "USA", displayName: "Detroit, USA" },
  { name: "Oklahoma City", country: "USA", displayName: "Oklahoma City, USA" },
  { name: "Portland", country: "USA", displayName: "Portland, USA" },
  { name: "Las Vegas", country: "USA", displayName: "Las Vegas, USA" },
  { name: "Memphis", country: "USA", displayName: "Memphis, USA" },
  { name: "Louisville", country: "USA", displayName: "Louisville, USA" },
  { name: "Baltimore", country: "USA", displayName: "Baltimore, USA" },
  { name: "Milwaukee", country: "USA", displayName: "Milwaukee, USA" },
  { name: "Albuquerque", country: "USA", displayName: "Albuquerque, USA" },
  { name: "Tucson", country: "USA", displayName: "Tucson, USA" },
  { name: "Fresno", country: "USA", displayName: "Fresno, USA" },
  { name: "Sacramento", country: "USA", displayName: "Sacramento, USA" },
  { name: "Kansas City", country: "USA", displayName: "Kansas City, USA" },
  { name: "Mesa", country: "USA", displayName: "Mesa, USA" },
  { name: "Atlanta", country: "USA", displayName: "Atlanta, USA" },
  { name: "Omaha", country: "USA", displayName: "Omaha, USA" },
  { name: "Colorado Springs", country: "USA", displayName: "Colorado Springs, USA" },
  { name: "Raleigh", country: "USA", displayName: "Raleigh, USA" },
  { name: "Miami", country: "USA", displayName: "Miami, USA" },
  { name: "Long Beach", country: "USA", displayName: "Long Beach, USA" },
  { name: "Virginia Beach", country: "USA", displayName: "Virginia Beach, USA" },
  { name: "Oakland", country: "USA", displayName: "Oakland, USA" },
  { name: "Minneapolis", country: "USA", displayName: "Minneapolis, USA" },
  { name: "Tulsa", country: "USA", displayName: "Tulsa, USA" },
  { name: "Tampa", country: "USA", displayName: "Tampa, USA" },
  { name: "Cleveland", country: "USA", displayName: "Cleveland, USA" },
  { name: "Wichita", country: "USA", displayName: "Wichita, USA" },
  { name: "Arlington", country: "USA", displayName: "Arlington, USA" },
  
  // UK - Major cities
  { name: "London", country: "UK", displayName: "London, UK" },
  { name: "Birmingham", country: "UK", displayName: "Birmingham, UK" },
  { name: "Manchester", country: "UK", displayName: "Manchester, UK" },
  { name: "Glasgow", country: "UK", displayName: "Glasgow, UK" },
  { name: "Liverpool", country: "UK", displayName: "Liverpool, UK" },
  { name: "Leeds", country: "UK", displayName: "Leeds, UK" },
  { name: "Sheffield", country: "UK", displayName: "Sheffield, UK" },
  { name: "Edinburgh", country: "UK", displayName: "Edinburgh, UK" },
  { name: "Bristol", country: "UK", displayName: "Bristol, UK" },
  { name: "Cardiff", country: "UK", displayName: "Cardiff, UK" },
  { name: "Belfast", country: "UK", displayName: "Belfast, UK" },
  { name: "Newcastle", country: "UK", displayName: "Newcastle, UK" },
  { name: "Nottingham", country: "UK", displayName: "Nottingham, UK" },
  { name: "Leicester", country: "UK", displayName: "Leicester, UK" },
  { name: "Coventry", country: "UK", displayName: "Coventry, UK" },
  { name: "Bradford", country: "UK", displayName: "Bradford, UK" },
  { name: "Sunderland", country: "UK", displayName: "Sunderland, UK" },
  { name: "Wolverhampton", country: "UK", displayName: "Wolverhampton, UK" },
  { name: "Plymouth", country: "UK", displayName: "Plymouth, UK" },
  { name: "Stoke-on-Trent", country: "UK", displayName: "Stoke-on-Trent, UK" },
  { name: "Reading", country: "UK", displayName: "Reading, UK" },
  { name: "Derby", country: "UK", displayName: "Derby, UK" },
  { name: "Southampton", country: "UK", displayName: "Southampton, UK" },
  { name: "Northampton", country: "UK", displayName: "Northampton, UK" },
  { name: "Portsmouth", country: "UK", displayName: "Portsmouth, UK" },
  { name: "Luton", country: "UK", displayName: "Luton, UK" },
  { name: "York", country: "UK", displayName: "York, UK" },
  { name: "Swindon", country: "UK", displayName: "Swindon, UK" },
  { name: "Peterborough", country: "UK", displayName: "Peterborough, UK" },
  { name: "Cambridge", country: "UK", displayName: "Cambridge, UK" },
  { name: "Oxford", country: "UK", displayName: "Oxford, UK" },
  
  // France - Major cities
  { name: "Paris", country: "France", displayName: "Paris, France" },
  { name: "Marseille", country: "France", displayName: "Marseille, France" },
  { name: "Lyon", country: "France", displayName: "Lyon, France" },
  { name: "Toulouse", country: "France", displayName: "Toulouse, France" },
  { name: "Nice", country: "France", displayName: "Nice, France" },
  { name: "Nantes", country: "France", displayName: "Nantes, France" },
  { name: "Strasbourg", country: "France", displayName: "Strasbourg, France" },
  { name: "Montpellier", country: "France", displayName: "Montpellier, France" },
  { name: "Bordeaux", country: "France", displayName: "Bordeaux, France" },
  { name: "Lille", country: "France", displayName: "Lille, France" },
  { name: "Rennes", country: "France", displayName: "Rennes, France" },
  { name: "Reims", country: "France", displayName: "Reims, France" },
  { name: "Le Havre", country: "France", displayName: "Le Havre, France" },
  { name: "Saint-Étienne", country: "France", displayName: "Saint-Étienne, France" },
  { name: "Toulon", country: "France", displayName: "Toulon, France" },
  
  // Canada - Major cities
  { name: "Toronto", country: "Canada", displayName: "Toronto, Canada" },
  { name: "Vancouver", country: "Canada", displayName: "Vancouver, Canada" },
  { name: "Montreal", country: "Canada", displayName: "Montreal, Canada" },
  { name: "Calgary", country: "Canada", displayName: "Calgary, Canada" },
  { name: "Edmonton", country: "Canada", displayName: "Edmonton, Canada" },
  { name: "Ottawa", country: "Canada", displayName: "Ottawa, Canada" },
  { name: "Winnipeg", country: "Canada", displayName: "Winnipeg, Canada" },
  { name: "Quebec City", country: "Canada", displayName: "Quebec City, Canada" },
  { name: "Hamilton", country: "Canada", displayName: "Hamilton, Canada" },
  { name: "Kitchener", country: "Canada", displayName: "Kitchener, Canada" },
  
  // Other major cities
  { name: "Amsterdam", country: "Netherlands", displayName: "Amsterdam, Netherlands" },
  { name: "Rotterdam", country: "Netherlands", displayName: "Rotterdam, Netherlands" },
  { name: "The Hague", country: "Netherlands", displayName: "The Hague, Netherlands" },
  { name: "Utrecht", country: "Netherlands", displayName: "Utrecht, Netherlands" },
  { name: "Eindhoven", country: "Netherlands", displayName: "Eindhoven, Netherlands" },
  
  { name: "Brussels", country: "Belgium", displayName: "Brussels, Belgium" },
  { name: "Antwerp", country: "Belgium", displayName: "Antwerp, Belgium" },
  { name: "Ghent", country: "Belgium", displayName: "Ghent, Belgium" },
  { name: "Bruges", country: "Belgium", displayName: "Bruges, Belgium" },
  
  { name: "Zurich", country: "Switzerland", displayName: "Zurich, Switzerland" },
  { name: "Geneva", country: "Switzerland", displayName: "Geneva, Switzerland" },
  { name: "Basel", country: "Switzerland", displayName: "Basel, Switzerland" },
  { name: "Bern", country: "Switzerland", displayName: "Bern, Switzerland" },
  
  { name: "Vienna", country: "Austria", displayName: "Vienna, Austria" },
  { name: "Graz", country: "Austria", displayName: "Graz, Austria" },
  { name: "Linz", country: "Austria", displayName: "Linz, Austria" },
  { name: "Salzburg", country: "Austria", displayName: "Salzburg, Austria" },
  
  { name: "Stockholm", country: "Sweden", displayName: "Stockholm, Sweden" },
  { name: "Gothenburg", country: "Sweden", displayName: "Gothenburg, Sweden" },
  { name: "Malmö", country: "Sweden", displayName: "Malmö, Sweden" },
  
  { name: "Copenhagen", country: "Denmark", displayName: "Copenhagen, Denmark" },
  { name: "Aarhus", country: "Denmark", displayName: "Aarhus, Denmark" },
  { name: "Odense", country: "Denmark", displayName: "Odense, Denmark" },
  
  { name: "Oslo", country: "Norway", displayName: "Oslo, Norway" },
  { name: "Bergen", country: "Norway", displayName: "Bergen, Norway" },
  { name: "Trondheim", country: "Norway", displayName: "Trondheim, Norway" },
  
  { name: "Helsinki", country: "Finland", displayName: "Helsinki, Finland" },
  { name: "Espoo", country: "Finland", displayName: "Espoo, Finland" },
  { name: "Tampere", country: "Finland", displayName: "Tampere, Finland" },
  
  { name: "Madrid", country: "Spain", displayName: "Madrid, Spain" },
  { name: "Barcelona", country: "Spain", displayName: "Barcelona, Spain" },
  { name: "Valencia", country: "Spain", displayName: "Valencia, Spain" },
  { name: "Seville", country: "Spain", displayName: "Seville, Spain" },
  { name: "Bilbao", country: "Spain", displayName: "Bilbao, Spain" },
  
  { name: "Rome", country: "Italy", displayName: "Rome, Italy" },
  { name: "Milan", country: "Italy", displayName: "Milan, Italy" },
  { name: "Naples", country: "Italy", displayName: "Naples, Italy" },
  { name: "Turin", country: "Italy", displayName: "Turin, Italy" },
  { name: "Palermo", country: "Italy", displayName: "Palermo, Italy" },
  { name: "Genoa", country: "Italy", displayName: "Genoa, Italy" },
  { name: "Bologna", country: "Italy", displayName: "Bologna, Italy" },
  { name: "Florence", country: "Italy", displayName: "Florence, Italy" },
  
  { name: "Sydney", country: "Australia", displayName: "Sydney, Australia" },
  { name: "Melbourne", country: "Australia", displayName: "Melbourne, Australia" },
  { name: "Brisbane", country: "Australia", displayName: "Brisbane, Australia" },
  { name: "Perth", country: "Australia", displayName: "Perth, Australia" },
  { name: "Adelaide", country: "Australia", displayName: "Adelaide, Australia" },
  
  { name: "Tokyo", country: "Japan", displayName: "Tokyo, Japan" },
  { name: "Yokohama", country: "Japan", displayName: "Yokohama, Japan" },
  { name: "Osaka", country: "Japan", displayName: "Osaka, Japan" },
  { name: "Nagoya", country: "Japan", displayName: "Nagoya, Japan" },
  { name: "Sapporo", country: "Japan", displayName: "Sapporo, Japan" },
  
  { name: "Beijing", country: "China", displayName: "Beijing, China" },
  { name: "Shanghai", country: "China", displayName: "Shanghai, China" },
  { name: "Guangzhou", country: "China", displayName: "Guangzhou, China" },
  { name: "Shenzhen", country: "China", displayName: "Shenzhen, China" },
  { name: "Chengdu", country: "China", displayName: "Chengdu, China" },
  
  { name: "Mumbai", country: "India", displayName: "Mumbai, India" },
  { name: "Delhi", country: "India", displayName: "Delhi, India" },
  { name: "Bangalore", country: "India", displayName: "Bangalore, India" },
  { name: "Hyderabad", country: "India", displayName: "Hyderabad, India" },
  { name: "Chennai", country: "India", displayName: "Chennai, India" },
  { name: "Kolkata", country: "India", displayName: "Kolkata, India" },
  { name: "Pune", country: "India", displayName: "Pune, India" },
  
  { name: "Singapore", country: "Singapore", displayName: "Singapore, Singapore" },
  { name: "Dubai", country: "UAE", displayName: "Dubai, UAE" },
  { name: "Abu Dhabi", country: "UAE", displayName: "Abu Dhabi, UAE" },
  { name: "Doha", country: "Qatar", displayName: "Doha, Qatar" },
  { name: "Riyadh", country: "Saudi Arabia", displayName: "Riyadh, Saudi Arabia" },
  { name: "Jeddah", country: "Saudi Arabia", displayName: "Jeddah, Saudi Arabia" },
  
  { name: "São Paulo", country: "Brazil", displayName: "São Paulo, Brazil" },
  { name: "Rio de Janeiro", country: "Brazil", displayName: "Rio de Janeiro, Brazil" },
  { name: "Brasília", country: "Brazil", displayName: "Brasília, Brazil" },
  { name: "Salvador", country: "Brazil", displayName: "Salvador, Brazil" },
  
  { name: "Buenos Aires", country: "Argentina", displayName: "Buenos Aires, Argentina" },
  { name: "Córdoba", country: "Argentina", displayName: "Córdoba, Argentina" },
  
  { name: "Mexico City", country: "Mexico", displayName: "Mexico City, Mexico" },
  { name: "Guadalajara", country: "Mexico", displayName: "Guadalajara, Mexico" },
  { name: "Monterrey", country: "Mexico", displayName: "Monterrey, Mexico" },
  
  { name: "São Paulo", country: "Brazil", displayName: "São Paulo, Brazil" },
  { name: "Lima", country: "Peru", displayName: "Lima, Peru" },
  { name: "Bogotá", country: "Colombia", displayName: "Bogotá, Colombia" },
  { name: "Santiago", country: "Chile", displayName: "Santiago, Chile" },
];

// Search function to filter cities based on query
export const searchCities = (query: string): City[] => {
  if (!query || query.length < 2) return [];
  
  const lowerQuery = query.toLowerCase().trim();
  
  return cities.filter(city => {
    const cityNameLower = city.name.toLowerCase();
    const countryLower = city.country.toLowerCase();
    const displayNameLower = city.displayName.toLowerCase();
    
    // Match if query is found in city name, country, or full display name
    return cityNameLower.includes(lowerQuery) || 
           countryLower.includes(lowerQuery) || 
           displayNameLower.includes(lowerQuery);
  }).slice(0, 10); // Limit to 10 results
};

